import css from "@eslint/css";
import js from "@eslint/js";
import json from "@eslint/json";
import tsPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";
import pluginReact from "eslint-plugin-react";
import { defineConfig } from "eslint/config";
import globals from "globals";

export default defineConfig([
  eslintPluginPrettierRecommended,
  {
    files: ["**/*.{js,mjs,cjs,jsx}"],
    plugins: { js },
    extends: ["js/recommended"],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },

  {
    ...pluginReact.configs.flat.recommended,
    rules: {
      "react/react-in-jsx-scope": "off",
      "react/jsx-uses-react": "off",
      "no-console": "warn",
      "prettier/prettier": [
        "error",
        {
          printWidth: 80,
        },
      ],
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    plugins: { "@typescript-eslint": tsPlugin },
    languageOptions: {
      parser: tsParser,
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": "warn",
    },
  },
  {
    // shadcn/ui components are generated by its CLI and re-generated on
    // update. They import React for type positions the JSX transform strips,
    // which reads as unused here. Exempt them rather than hand-editing:
    // an edit would be silently reverted the next time one is regenerated.
    files: ["src/admin/components/ui/**"],
    rules: {
      "no-unused-vars": "off",
    },
  },
  {
    files: ["**/*.json"],
    plugins: { json },
    language: "json/json",
    extends: ["json/recommended"],
  },
  {
    files: ["**/*.css"],
    // The Tailwind entry stylesheet is excluded: @eslint/css cannot parse
    // Tailwind v4's at-rule syntax (`prefix()`, `@custom-variant`,
    // `@theme inline`), so every "error" it reports there is a false
    // positive. Any other CSS in the project is still linted.
    ignores: ["src/admin/index.css"],
    plugins: { css },
    language: "css/css",
    extends: ["css/recommended"],
  },
]);
